[build]
  # Directory with the build command and publish directory
  base = "daily-brief-frontend"
  # Build command
  command = "npm run build"
  # Directory to publish
  publish = "daily-brief-frontend/.next"

# Ensure the Next.js plugin runs
[[plugins]]
  package = "@netlify/plugin-nextjs" 