name: Auto Deploy Newsletters

on:
  # Run when changes are detected in the daily brief intelligence folder
  push:
    paths:
      - 'daily brief intelligence/newsletter_*.md'
  
  # Also run on a schedule (every day at midnight)
  schedule:
    - cron: '0 0 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          cd new-daily-brief
          npm ci
          npm run build
          npx netlify-cli deploy --prod 